"builtin.module"() ({
  "func.func"() <{sym_name = "forward", function_type = (tensor<16xf32>, tensor<16xi32>, tensor<16xf32>, tensor<16xi32>, tensor<128x128xf32>, tensor<128x128xf32>) -> tensor<128x128xf32>}> ({
  ^bb0(%0: tensor<16xf32>, %1: tensor<16xi32>, %2: tensor<16xf32>, %3: tensor<16xi32>, %4: tensor<128x128xf32>, %5: tensor<128x128xf32>):
    %6 = "tensor.empty"() {prov.region_id = "dtype_cast_0", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %7 = "linalg.generic"(%4, %6) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb1(%8: f32, %9: bf16):
      %10 = "arith.truncf"(%8) {prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%10) {prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_0", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x128xf32>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %11 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %12 = "linalg.transpose"(%7, %11) <{permutation = array<i64: 0, 1>}> ({
    ^bb2(%13: bf16, %14: bf16):
      "linalg.yield"(%13) {prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_0", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_0"} : (tensor<128x128xbf16>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %15 = "tensor.empty"() {prov.region_id = "dtype_cast_1", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x128xf32>
    %16 = "linalg.generic"(%12, %15) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb3(%17: bf16, %18: f32):
      %19 = "arith.extf"(%17) {prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%19) {prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_1", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x128xbf16>, tensor<128x128xf32>) -> tensor<128x128xf32>
    %20 = "tensor.collapse_shape"(%16) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "view_0", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n11"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n11"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x128xf32>) -> tensor<16384xf32>
    %21 = "tensor.expand_shape"(%20) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 4, 32>}> {prov.region_id = "view_0", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n11"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n11"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32xf32>
    %22 = "tensor.empty"() {prov.region_id = "abs_0", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %23 = "linalg.generic"(%21, %22) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb4(%24: f32, %25: f32):
      %26 = "math.absf"(%24) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%26) {prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_0", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %27 = "arith.constant"() <{value = 0xff800000 : f32}> {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : () -> f32
    %28 = "tensor.splat"(%27) {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x4xf32>
    %29 = "linalg.reduce"(%23, %28) <{dimensions = array<i64: 2>}> ({
    ^bb5(%30: f32, %31: f32):
      %32 = "arith.maximumf"(%30, %31) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%32) {prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %33 = "tensor.empty"() {prov.region_id = "minmax_0", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %34 = "linalg.generic"(%29, %33) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb6(%35: f32, %36: f32):
      %37 = "arith.constant"() <{value = 1.1920929e-07 : f32}> {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : () -> f32
      %38 = "arith.cmpf"(%35, %37) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %39 = "arith.select"(%38, %37, %35) {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%39) {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_0", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %40 = "tensor.empty"() {prov.region_id = "log2_0", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %41 = "linalg.generic"(%34, %40) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb7(%42: f32, %43: f32):
      %44 = "math.log2"(%42) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%44) {prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "log2_0", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %45 = "tensor.empty"() {prov.region_id = "floor_0", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %46 = "linalg.generic"(%41, %45) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb8(%47: f32, %48: f32):
      %49 = "math.floor"(%47) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%49) {prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "floor_0", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %50 = "tensor.empty"() {prov.region_id = "minmax_1", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %51 = "linalg.generic"(%46, %50) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb9(%52: f32, %53: f32):
      %54 = "arith.constant"() <{value = -2.300000e+01 : f32}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : () -> f32
      %55 = "arith.cmpf"(%52, %54) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %56 = "arith.select"(%55, %54, %52) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      %57 = "arith.constant"() <{value = 1.270000e+02 : f32}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : () -> f32
      %58 = "arith.cmpf"(%56, %57) <{predicate = 2 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %59 = "arith.select"(%58, %57, %56) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%59) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_1", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %60 = "tensor.empty"() {prov.region_id = "exp2_0", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %61 = "linalg.generic"(%51, %60) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb10(%62: f32, %63: f32):
      %64 = "math.exp2"(%62) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%64) {prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "exp2_0", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %65 = "tensor.collapse_shape"(%61) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "unsqueeze_0", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n19"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n19"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>) -> tensor<512xf32>
    %66 = "tensor.expand_shape"(%65) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 4, 1>}> {prov.region_id = "unsqueeze_0", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n19"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n19"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<512xf32>) -> tensor<128x4x1xf32>
    %67 = "tensor.empty"() {prov.region_id = "div_0", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %68 = "linalg.generic"(%21, %66, %67) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb11(%69: f32, %70: f32, %71: f32):
      %72 = "arith.divf"(%69, %70) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%72) {prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "div_0", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x1xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %73 = "tensor.collapse_shape"(%68) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "unsqueeze_1", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n23"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n25"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %74 = "tensor.expand_shape"(%73) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 4, 32, 1>}> {prov.region_id = "unsqueeze_1", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n23"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n25"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32x1xf32>
    %75 = "tensor.empty"() {prov.region_id = "sub_0", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32x16xf32>
    %76 = "linalg.generic"(%74, %0, %75) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb12(%77: f32, %78: f32, %79: f32):
      %80 = "arith.subf"(%77, %78) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%80) {prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "sub_0", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32x1xf32>, tensor<16xf32>, tensor<128x4x32x16xf32>) -> tensor<128x4x32x16xf32>
    %81 = "tensor.empty"() {prov.region_id = "abs_1", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x4x32x16xf32>
    %82 = "linalg.generic"(%76, %81) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb13(%83: f32, %84: f32):
      %85 = "math.absf"(%83) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%85) {prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_1", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x4x32x16xf32>, tensor<128x4x32x16xf32>) -> tensor<128x4x32x16xf32>
    %86 = "arith.constant"() <{value = 0x7f800000 : f32}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : () -> f32
    %87 = "tensor.splat"(%86) {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x4x32xf32>
    %88 = "linalg.reduce"(%82, %87) <{dimensions = array<i64: 3>}> ({
    ^bb14(%89: f32, %90: f32):
      %91 = "arith.minimumf"(%89, %90) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%91) {prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x4x32x16xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %92 = "tensor.collapse_shape"(%88) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %93 = "tensor.expand_shape"(%92) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 4, 32, 1>}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32x1xf32>
    %94 = "tensor.empty"() {prov.region_id = "compare_0", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : () -> tensor<128x4x32x16xi1>
    %95 = "linalg.generic"(%82, %93, %94) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb15(%96: f32, %97: f32, %98: i1):
      %99 = "arith.cmpf"(%96, %97) <{predicate = 1 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      "linalg.yield"(%99) {prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering"} : (i1) -> ()
    }) {prov.region_id = "compare_0", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : (tensor<128x4x32x16xf32>, tensor<128x4x32x1xf32>, tensor<128x4x32x16xi1>) -> tensor<128x4x32x16xi1>
    %100 = "arith.constant"() <{value = 1024 : i32}> {prov.region_id = "fill_0", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n28"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n30"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : () -> i32
    %101 = "tensor.splat"(%100) {prov.region_id = "fill_0", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n28"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n30"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : (i32) -> tensor<16xi32>
    %102 = "tensor.empty"() {prov.region_id = "select_0", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : () -> tensor<128x4x32x16xi32>
    %103 = "linalg.generic"(%95, %1, %101, %102) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 3, 1>}> ({
    ^bb16(%104: i1, %105: i32, %106: i32, %107: i32):
      %108 = "arith.select"(%104, %105, %106) {prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      "linalg.yield"(%108) {prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering"} : (i32) -> ()
    }) {prov.region_id = "select_0", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : (tensor<128x4x32x16xi1>, tensor<16xi32>, tensor<16xi32>, tensor<128x4x32x16xi32>) -> tensor<128x4x32x16xi32>
    %109 = "arith.constant"() <{value = 2147483647 : i32}> {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i32
    %110 = "arith.constant"() <{value = 9223372036854775807 : i64}> {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i64
    %111 = "tensor.splat"(%109) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i32) -> tensor<128x4x32xi32>
    %112 = "tensor.splat"(%110) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i64) -> tensor<128x4x32xi64>
    %113, %114 = "linalg.generic"(%103, %111, %112) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<reduction>], operandSegmentSizes = array<i32: 1, 2>}> ({
    ^bb17(%115: i32, %116: i32, %117: i64):
      %118 = "linalg.index"() <{dim = 3 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : () -> index
      %119 = "arith.index_cast"(%118) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (index) -> i64
      %120 = "arith.cmpi"(%115, %116) <{predicate = 2 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %121 = "arith.cmpi"(%115, %116) <{predicate = 0 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %122 = "arith.cmpi"(%119, %117) <{predicate = 6 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i64, i64) -> i1
      %123 = "arith.andi"(%121, %122) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %124 = "arith.ori"(%120, %123) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %125 = "arith.select"(%124, %115, %116) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      %126 = "arith.select"(%124, %119, %117) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i64, i64) -> i64
      "linalg.yield"(%125, %126) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i64) -> ()
    }) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (tensor<128x4x32x16xi32>, tensor<128x4x32xi32>, tensor<128x4x32xi64>) -> (tensor<128x4x32xi32>, tensor<128x4x32xi64>)
    %127 = "tensor.empty"() {prov.region_id = "gather_0", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %128 = "linalg.generic"(%114, %127) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb18(%129: i64, %130: f32):
      %131 = "arith.index_cast"(%129) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (i64) -> index
      %132 = "tensor.extract"(%0, %131) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (tensor<16xf32>, index) -> f32
      "linalg.yield"(%132) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "gather_0", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xi64>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %133 = "tensor.empty"() {prov.region_id = "mul_0", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %134 = "linalg.generic"(%128, %66, %133) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb19(%135: f32, %136: f32, %137: f32):
      %138 = "arith.mulf"(%135, %136) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%138) {prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "mul_0", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x1xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %139 = "tensor.collapse_shape"(%134) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "view_1", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n33"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n35"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %140 = "tensor.expand_shape"(%139) <{reassociation = [[0 : i64, 1 : i64]], static_output_shape = array<i64: 128, 128>}> {prov.region_id = "view_1", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n33"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n35"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x128xf32>
    %141 = "tensor.empty"() {prov.region_id = "dtype_cast_2", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %142 = "linalg.generic"(%140, %141) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb20(%143: f32, %144: bf16):
      %145 = "arith.truncf"(%143) {prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%145) {prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_2", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x128xf32>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %146 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %147 = "linalg.transpose"(%142, %146) <{permutation = array<i64: 0, 1>}> ({
    ^bb21(%148: bf16, %149: bf16):
      "linalg.yield"(%148) {prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_1", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_1"} : (tensor<128x128xbf16>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %150 = "tensor.empty"() {prov.region_id = "dtype_cast_3", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x128xf32>
    %151 = "linalg.generic"(%147, %150) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb22(%152: bf16, %153: f32):
      %154 = "arith.extf"(%152) {prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%154) {prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_3", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x128xbf16>, tensor<128x128xf32>) -> tensor<128x128xf32>
    %155 = "tensor.empty"() {prov.region_id = "dtype_cast_4", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %156 = "linalg.generic"(%5, %155) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb23(%157: f32, %158: bf16):
      %159 = "arith.truncf"(%157) {prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%159) {prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_4", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x128xf32>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %160 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %161 = "linalg.transpose"(%156, %160) <{permutation = array<i64: 1, 0>}> ({
    ^bb24(%162: bf16, %163: bf16):
      "linalg.yield"(%162) {prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_2", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_2"} : (tensor<128x128xbf16>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %164 = "tensor.empty"() {prov.region_id = "dtype_cast_5", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x128xf32>
    %165 = "linalg.generic"(%161, %164) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb25(%166: bf16, %167: f32):
      %168 = "arith.extf"(%166) {prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%168) {prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_5", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x128xbf16>, tensor<128x128xf32>) -> tensor<128x128xf32>
    %169 = "tensor.collapse_shape"(%165) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "view_2", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n44"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n46"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x128xf32>) -> tensor<16384xf32>
    %170 = "tensor.expand_shape"(%169) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 4, 32>}> {prov.region_id = "view_2", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n44"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n46"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32xf32>
    %171 = "tensor.empty"() {prov.region_id = "abs_2", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %172 = "linalg.generic"(%170, %171) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb26(%173: f32, %174: f32):
      %175 = "math.absf"(%173) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%175) {prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_2", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %176 = "arith.constant"() <{value = 0xff800000 : f32}> {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : () -> f32
    %177 = "tensor.splat"(%176) {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x4xf32>
    %178 = "linalg.reduce"(%172, %177) <{dimensions = array<i64: 2>}> ({
    ^bb27(%179: f32, %180: f32):
      %181 = "arith.maximumf"(%179, %180) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%181) {prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %182 = "tensor.empty"() {prov.region_id = "minmax_2", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %183 = "linalg.generic"(%178, %182) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb28(%184: f32, %185: f32):
      %186 = "arith.constant"() <{value = 1.1920929e-07 : f32}> {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : () -> f32
      %187 = "arith.cmpf"(%184, %186) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %188 = "arith.select"(%187, %186, %184) {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%188) {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_2", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %189 = "tensor.empty"() {prov.region_id = "log2_1", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %190 = "linalg.generic"(%183, %189) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb29(%191: f32, %192: f32):
      %193 = "math.log2"(%191) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%193) {prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "log2_1", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %194 = "tensor.empty"() {prov.region_id = "floor_1", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %195 = "linalg.generic"(%190, %194) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb30(%196: f32, %197: f32):
      %198 = "math.floor"(%196) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%198) {prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "floor_1", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %199 = "tensor.empty"() {prov.region_id = "minmax_3", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %200 = "linalg.generic"(%195, %199) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb31(%201: f32, %202: f32):
      %203 = "arith.constant"() <{value = -2.300000e+01 : f32}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : () -> f32
      %204 = "arith.cmpf"(%201, %203) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %205 = "arith.select"(%204, %203, %201) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      %206 = "arith.constant"() <{value = 1.270000e+02 : f32}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : () -> f32
      %207 = "arith.cmpf"(%205, %206) <{predicate = 2 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %208 = "arith.select"(%207, %206, %205) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%208) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_3", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %209 = "tensor.empty"() {prov.region_id = "exp2_1", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : () -> tensor<128x4xf32>
    %210 = "linalg.generic"(%200, %209) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb32(%211: f32, %212: f32):
      %213 = "math.exp2"(%211) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%213) {prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "exp2_1", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>, tensor<128x4xf32>) -> tensor<128x4xf32>
    %214 = "tensor.collapse_shape"(%210) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "unsqueeze_2", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n52"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n54"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x4xf32>) -> tensor<512xf32>
    %215 = "tensor.expand_shape"(%214) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 4, 1>}> {prov.region_id = "unsqueeze_2", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n52"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n54"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<512xf32>) -> tensor<128x4x1xf32>
    %216 = "tensor.empty"() {prov.region_id = "div_1", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %217 = "linalg.generic"(%170, %215, %216) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb33(%218: f32, %219: f32, %220: f32):
      %221 = "arith.divf"(%218, %219) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%221) {prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "div_1", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x1xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %222 = "tensor.collapse_shape"(%217) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "unsqueeze_3", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n56"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n60"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %223 = "tensor.expand_shape"(%222) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 4, 32, 1>}> {prov.region_id = "unsqueeze_3", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n56"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n60"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32x1xf32>
    %224 = "tensor.empty"() {prov.region_id = "sub_1", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32x16xf32>
    %225 = "linalg.generic"(%223, %2, %224) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb34(%226: f32, %227: f32, %228: f32):
      %229 = "arith.subf"(%226, %227) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%229) {prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "sub_1", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32x1xf32>, tensor<16xf32>, tensor<128x4x32x16xf32>) -> tensor<128x4x32x16xf32>
    %230 = "tensor.empty"() {prov.region_id = "abs_3", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x4x32x16xf32>
    %231 = "linalg.generic"(%225, %230) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb35(%232: f32, %233: f32):
      %234 = "math.absf"(%232) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%234) {prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_3", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x4x32x16xf32>, tensor<128x4x32x16xf32>) -> tensor<128x4x32x16xf32>
    %235 = "arith.constant"() <{value = 0x7f800000 : f32}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : () -> f32
    %236 = "tensor.splat"(%235) {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x4x32xf32>
    %237 = "linalg.reduce"(%231, %236) <{dimensions = array<i64: 3>}> ({
    ^bb36(%238: f32, %239: f32):
      %240 = "arith.minimumf"(%238, %239) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%240) {prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x4x32x16xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %241 = "tensor.collapse_shape"(%237) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %242 = "tensor.expand_shape"(%241) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 4, 32, 1>}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x4x32x1xf32>
    %243 = "tensor.empty"() {prov.region_id = "compare_1", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : () -> tensor<128x4x32x16xi1>
    %244 = "linalg.generic"(%231, %242, %243) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb37(%245: f32, %246: f32, %247: i1):
      %248 = "arith.cmpf"(%245, %246) <{predicate = 1 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      "linalg.yield"(%248) {prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering"} : (i1) -> ()
    }) {prov.region_id = "compare_1", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : (tensor<128x4x32x16xf32>, tensor<128x4x32x1xf32>, tensor<128x4x32x16xi1>) -> tensor<128x4x32x16xi1>
    %249 = "arith.constant"() <{value = 1024 : i32}> {prov.region_id = "fill_1", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n61"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n65"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : () -> i32
    %250 = "tensor.splat"(%249) {prov.region_id = "fill_1", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n61"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n65"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : (i32) -> tensor<16xi32>
    %251 = "tensor.empty"() {prov.region_id = "select_1", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : () -> tensor<128x4x32x16xi32>
    %252 = "linalg.generic"(%244, %3, %250, %251) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 3, 1>}> ({
    ^bb38(%253: i1, %254: i32, %255: i32, %256: i32):
      %257 = "arith.select"(%253, %254, %255) {prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      "linalg.yield"(%257) {prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering"} : (i32) -> ()
    }) {prov.region_id = "select_1", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : (tensor<128x4x32x16xi1>, tensor<16xi32>, tensor<16xi32>, tensor<128x4x32x16xi32>) -> tensor<128x4x32x16xi32>
    %258 = "arith.constant"() <{value = 2147483647 : i32}> {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i32
    %259 = "arith.constant"() <{value = 9223372036854775807 : i64}> {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i64
    %260 = "tensor.splat"(%258) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i32) -> tensor<128x4x32xi32>
    %261 = "tensor.splat"(%259) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i64) -> tensor<128x4x32xi64>
    %262, %263 = "linalg.generic"(%252, %260, %261) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<reduction>], operandSegmentSizes = array<i32: 1, 2>}> ({
    ^bb39(%264: i32, %265: i32, %266: i64):
      %267 = "linalg.index"() <{dim = 3 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : () -> index
      %268 = "arith.index_cast"(%267) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (index) -> i64
      %269 = "arith.cmpi"(%264, %265) <{predicate = 2 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %270 = "arith.cmpi"(%264, %265) <{predicate = 0 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %271 = "arith.cmpi"(%268, %266) <{predicate = 6 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i64, i64) -> i1
      %272 = "arith.andi"(%270, %271) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %273 = "arith.ori"(%269, %272) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %274 = "arith.select"(%273, %264, %265) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      %275 = "arith.select"(%273, %268, %266) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i64, i64) -> i64
      "linalg.yield"(%274, %275) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i64) -> ()
    }) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (tensor<128x4x32x16xi32>, tensor<128x4x32xi32>, tensor<128x4x32xi64>) -> (tensor<128x4x32xi32>, tensor<128x4x32xi64>)
    %276 = "tensor.empty"() {prov.region_id = "gather_1", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %277 = "linalg.generic"(%263, %276) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb40(%278: i64, %279: f32):
      %280 = "arith.index_cast"(%278) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (i64) -> index
      %281 = "tensor.extract"(%2, %280) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (tensor<16xf32>, index) -> f32
      "linalg.yield"(%281) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "gather_1", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xi64>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %282 = "tensor.empty"() {prov.region_id = "mul_1", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x4x32xf32>
    %283 = "linalg.generic"(%277, %215, %282) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb41(%284: f32, %285: f32, %286: f32):
      %287 = "arith.mulf"(%284, %285) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%287) {prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "mul_1", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>, tensor<128x4x1xf32>, tensor<128x4x32xf32>) -> tensor<128x4x32xf32>
    %288 = "tensor.collapse_shape"(%283) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "view_3", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n66"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n70"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x4x32xf32>) -> tensor<16384xf32>
    %289 = "tensor.expand_shape"(%288) <{reassociation = [[0 : i64, 1 : i64]], static_output_shape = array<i64: 128, 128>}> {prov.region_id = "view_3", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n66"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n70"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<16384xf32>) -> tensor<128x128xf32>
    %290 = "tensor.empty"() {prov.region_id = "dtype_cast_6", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %291 = "linalg.generic"(%289, %290) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb42(%292: f32, %293: bf16):
      %294 = "arith.truncf"(%292) {prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%294) {prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_6", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x128xf32>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %295 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x128xbf16>
    %296 = "linalg.transpose"(%291, %295) <{permutation = array<i64: 1, 0>}> ({
    ^bb43(%297: bf16, %298: bf16):
      "linalg.yield"(%297) {prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_3", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_3"} : (tensor<128x128xbf16>, tensor<128x128xbf16>) -> tensor<128x128xbf16>
    %299 = "tensor.empty"() {prov.region_id = "dtype_cast_7", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x128xf32>
    %300 = "linalg.generic"(%296, %299) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb44(%301: bf16, %302: f32):
      %303 = "arith.extf"(%301) {prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%303) {prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_7", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x128xbf16>, tensor<128x128xf32>) -> tensor<128x128xf32>
    %304 = "arith.constant"() <{value = 0.000000e+00 : f32}> {prov.region_id = "matmul_0", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : () -> f32
    %305 = "tensor.splat"(%304) {prov.region_id = "matmul_0", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x128xf32>
    %306 = "linalg.matmul"(%151, %300, %305) <{operandSegmentSizes = array<i32: 2, 1>, indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d2, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>]}> ({
    ^bb45(%307: f32, %308: f32, %309: f32):
      %310 = "arith.mulf"(%307, %308) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      %311 = "arith.addf"(%310, %309) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%311) {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "matmul_0", prov.op = "matmul", prov.family = "contraction", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : (tensor<128x128xf32>, tensor<128x128xf32>, tensor<128x128xf32>) -> tensor<128x128xf32>
    "func.return"(%306) : (tensor<128x128xf32>) -> ()
  }) : () -> ()
}) {prov.level = "linalg-on-tensors", prov.quantization = "external:mx_gemmini", prov.quantization_manifest_sha256 = "8f91190c78c414abf90c3327959dc1e386113437bc6678d48e646f6d269b1b24"} : () -> ()
