"builtin.module"() ({
  "func.func"() <{sym_name = "forward", function_type = (tensor<16xf32>, tensor<16xi32>, tensor<16xf32>, tensor<16xi32>, tensor<128x512xf32>, tensor<512x128xf32>) -> tensor<128x128xf32>}> ({
  ^bb0(%0: tensor<16xf32>, %1: tensor<16xi32>, %2: tensor<16xf32>, %3: tensor<16xi32>, %4: tensor<128x512xf32>, %5: tensor<512x128xf32>):
    %6 = "tensor.empty"() {prov.region_id = "dtype_cast_0", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %7 = "linalg.generic"(%4, %6) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb1(%8: f32, %9: bf16):
      %10 = "arith.truncf"(%8) {prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%10) {prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_0", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n7"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n7"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x512xf32>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %11 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %12 = "linalg.transpose"(%7, %11) <{permutation = array<i64: 0, 1>}> ({
    ^bb2(%13: bf16, %14: bf16):
      "linalg.yield"(%13) {prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_0", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n8"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n8"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_0"} : (tensor<128x512xbf16>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %15 = "tensor.empty"() {prov.region_id = "dtype_cast_1", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x512xf32>
    %16 = "linalg.generic"(%12, %15) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb3(%17: bf16, %18: f32):
      %19 = "arith.extf"(%17) {prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%19) {prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_1", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n10"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n10"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x512xbf16>, tensor<128x512xf32>) -> tensor<128x512xf32>
    %20 = "tensor.collapse_shape"(%16) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "view_0", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n11"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n11"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x512xf32>) -> tensor<65536xf32>
    %21 = "tensor.expand_shape"(%20) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 16, 32>}> {prov.region_id = "view_0", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n11"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n11"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32xf32>
    %22 = "tensor.empty"() {prov.region_id = "abs_0", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %23 = "linalg.generic"(%21, %22) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb4(%24: f32, %25: f32):
      %26 = "math.absf"(%24) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%26) {prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_0", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n12"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n12"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %27 = "arith.constant"() <{value = 0xff800000 : f32}> {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : () -> f32
    %28 = "tensor.splat"(%27) {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x16xf32>
    %29 = "linalg.reduce"(%23, %28) <{dimensions = array<i64: 2>}> ({
    ^bb5(%30: f32, %31: f32):
      %32 = "arith.maximumf"(%30, %31) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%32) {prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_0", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n13"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n13"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %33 = "tensor.empty"() {prov.region_id = "minmax_0", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %34 = "linalg.generic"(%29, %33) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb6(%35: f32, %36: f32):
      %37 = "arith.constant"() <{value = 1.1920929e-07 : f32}> {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : () -> f32
      %38 = "arith.cmpf"(%35, %37) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %39 = "arith.select"(%38, %37, %35) {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%39) {prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_0", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n14"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n14"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %40 = "tensor.empty"() {prov.region_id = "log2_0", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %41 = "linalg.generic"(%34, %40) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb7(%42: f32, %43: f32):
      %44 = "math.log2"(%42) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%44) {prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "log2_0", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n15"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n15"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %45 = "tensor.empty"() {prov.region_id = "floor_0", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %46 = "linalg.generic"(%41, %45) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb8(%47: f32, %48: f32):
      %49 = "math.floor"(%47) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%49) {prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "floor_0", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n16"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n16"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %50 = "tensor.empty"() {prov.region_id = "minmax_1", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %51 = "linalg.generic"(%46, %50) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb9(%52: f32, %53: f32):
      %54 = "arith.constant"() <{value = -23 : i64}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : () -> i64
      %55 = "arith.sitofp"(%54) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i64) -> f32
      %56 = "arith.cmpf"(%52, %55) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %57 = "arith.select"(%56, %55, %52) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      %58 = "arith.constant"() <{value = 127 : i64}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : () -> i64
      %59 = "arith.sitofp"(%58) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i64) -> f32
      %60 = "arith.cmpf"(%57, %59) <{predicate = 2 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %61 = "arith.select"(%60, %59, %57) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%61) {prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_1", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n17"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n17"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %62 = "tensor.empty"() {prov.region_id = "exp2_0", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %63 = "linalg.generic"(%51, %62) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb10(%64: f32, %65: f32):
      %66 = "math.exp2"(%64) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%66) {prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "exp2_0", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n18"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n18"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %67 = "tensor.collapse_shape"(%63) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "unsqueeze_0", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n19"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n19"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>) -> tensor<2048xf32>
    %68 = "tensor.expand_shape"(%67) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 16, 1>}> {prov.region_id = "unsqueeze_0", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n19"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n19"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<2048xf32>) -> tensor<128x16x1xf32>
    %69 = "tensor.empty"() {prov.region_id = "div_0", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %70 = "linalg.generic"(%21, %68, %69) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb11(%71: f32, %72: f32, %73: f32):
      %74 = "arith.divf"(%71, %72) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%74) {prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "div_0", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n20"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n20"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x1xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %75 = "tensor.collapse_shape"(%70) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "unsqueeze_1", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n23"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n25"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %76 = "tensor.expand_shape"(%75) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 16, 32, 1>}> {prov.region_id = "unsqueeze_1", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n23"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n25"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32x1xf32>
    %77 = "tensor.empty"() {prov.region_id = "sub_0", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32x16xf32>
    %78 = "linalg.generic"(%76, %0, %77) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb12(%79: f32, %80: f32, %81: f32):
      %82 = "arith.subf"(%79, %80) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%82) {prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "sub_0", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n24"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n26"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32x1xf32>, tensor<16xf32>, tensor<128x16x32x16xf32>) -> tensor<128x16x32x16xf32>
    %83 = "tensor.empty"() {prov.region_id = "abs_1", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x16x32x16xf32>
    %84 = "linalg.generic"(%78, %83) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb13(%85: f32, %86: f32):
      %87 = "math.absf"(%85) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%87) {prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_1", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n25"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n27"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x16x32x16xf32>, tensor<128x16x32x16xf32>) -> tensor<128x16x32x16xf32>
    %88 = "arith.constant"() <{value = 0x7f800000 : f32}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : () -> f32
    %89 = "tensor.splat"(%88) {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x16x32xf32>
    %90 = "linalg.reduce"(%84, %89) <{dimensions = array<i64: 3>}> ({
    ^bb14(%91: f32, %92: f32):
      %93 = "arith.minimumf"(%91, %92) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%93) {prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x16x32x16xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %94 = "tensor.collapse_shape"(%90) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %95 = "tensor.expand_shape"(%94) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 16, 32, 1>}> {prov.region_id = "reduce_1", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n26"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n28"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32x1xf32>
    %96 = "tensor.empty"() {prov.region_id = "compare_0", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : () -> tensor<128x16x32x16xi1>
    %97 = "linalg.generic"(%84, %95, %96) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb15(%98: f32, %99: f32, %100: i1):
      %101 = "arith.cmpf"(%98, %99) <{predicate = 1 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      "linalg.yield"(%101) {prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering"} : (i1) -> ()
    }) {prov.region_id = "compare_0", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n27"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n29"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : (tensor<128x16x32x16xf32>, tensor<128x16x32x1xf32>, tensor<128x16x32x16xi1>) -> tensor<128x16x32x16xi1>
    %102 = "arith.constant"() <{value = 1024 : i32}> {prov.region_id = "fill_0", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n28"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n30"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : () -> i32
    %103 = "tensor.splat"(%102) {prov.region_id = "fill_0", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n28"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n30"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : (i32) -> tensor<16xi32>
    %104 = "tensor.empty"() {prov.region_id = "select_0", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : () -> tensor<128x16x32x16xi32>
    %105 = "linalg.generic"(%97, %1, %103, %104) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 3, 1>}> ({
    ^bb16(%106: i1, %107: i32, %108: i32, %109: i32):
      %110 = "arith.select"(%106, %107, %108) {prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      "linalg.yield"(%110) {prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering"} : (i32) -> ()
    }) {prov.region_id = "select_0", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n29"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n31"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : (tensor<128x16x32x16xi1>, tensor<16xi32>, tensor<16xi32>, tensor<128x16x32x16xi32>) -> tensor<128x16x32x16xi32>
    %111 = "arith.constant"() <{value = 2147483647 : i32}> {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i32
    %112 = "arith.constant"() <{value = 9223372036854775807 : i64}> {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i64
    %113 = "tensor.splat"(%111) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i32) -> tensor<128x16x32xi32>
    %114 = "tensor.splat"(%112) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i64) -> tensor<128x16x32xi64>
    %115, %116 = "linalg.generic"(%105, %113, %114) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<reduction>], operandSegmentSizes = array<i32: 1, 2>}> ({
    ^bb17(%117: i32, %118: i32, %119: i64):
      %120 = "linalg.index"() <{dim = 3 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : () -> index
      %121 = "arith.index_cast"(%120) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (index) -> i64
      %122 = "arith.cmpi"(%117, %118) <{predicate = 2 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %123 = "arith.cmpi"(%117, %118) <{predicate = 0 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %124 = "arith.cmpi"(%121, %119) <{predicate = 6 : i64}> {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i64, i64) -> i1
      %125 = "arith.andi"(%123, %124) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %126 = "arith.ori"(%122, %125) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %127 = "arith.select"(%126, %117, %118) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      %128 = "arith.select"(%126, %121, %119) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i1, i64, i64) -> i64
      "linalg.yield"(%127, %128) {prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering"} : (i32, i64) -> ()
    }) {prov.region_id = "arg_reduce_0", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n30"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n32"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (tensor<128x16x32x16xi32>, tensor<128x16x32xi32>, tensor<128x16x32xi64>) -> (tensor<128x16x32xi32>, tensor<128x16x32xi64>)
    %129 = "tensor.empty"() {prov.region_id = "gather_0", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %130 = "linalg.generic"(%116, %129) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb18(%131: i64, %132: f32):
      %133 = "arith.index_cast"(%131) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (i64) -> index
      %134 = "tensor.extract"(%0, %133) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (tensor<16xf32>, index) -> f32
      "linalg.yield"(%134) {prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "gather_0", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n31"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n33"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xi64>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %135 = "tensor.empty"() {prov.region_id = "mul_0", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %136 = "linalg.generic"(%130, %68, %135) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb19(%137: f32, %138: f32, %139: f32):
      %140 = "arith.mulf"(%137, %138) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%140) {prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "mul_0", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n32"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n34"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x1xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %141 = "tensor.collapse_shape"(%136) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "view_1", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n33"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n35"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %142 = "tensor.expand_shape"(%141) <{reassociation = [[0 : i64, 1 : i64]], static_output_shape = array<i64: 128, 512>}> {prov.region_id = "view_1", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n33"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n35"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x512xf32>
    %143 = "tensor.empty"() {prov.region_id = "dtype_cast_2", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %144 = "linalg.generic"(%142, %143) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb20(%145: f32, %146: bf16):
      %147 = "arith.truncf"(%145) {prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%147) {prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_2", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n35"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n37"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x512xf32>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %148 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %149 = "linalg.transpose"(%144, %148) <{permutation = array<i64: 0, 1>}> ({
    ^bb21(%150: bf16, %151: bf16):
      "linalg.yield"(%150) {prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_1", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n36"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n38"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_1"} : (tensor<128x512xbf16>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %152 = "tensor.empty"() {prov.region_id = "dtype_cast_3", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x512xf32>
    %153 = "linalg.generic"(%149, %152) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb22(%154: bf16, %155: f32):
      %156 = "arith.extf"(%154) {prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%156) {prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_3", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n38"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n40"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x512xbf16>, tensor<128x512xf32>) -> tensor<128x512xf32>
    %157 = "tensor.empty"() {prov.region_id = "dtype_cast_4", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<512x128xbf16>
    %158 = "linalg.generic"(%5, %157) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb23(%159: f32, %160: bf16):
      %161 = "arith.truncf"(%159) {prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%161) {prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_4", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n40"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n42"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<512x128xf32>, tensor<512x128xbf16>) -> tensor<512x128xbf16>
    %162 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %163 = "linalg.transpose"(%158, %162) <{permutation = array<i64: 1, 0>}> ({
    ^bb24(%164: bf16, %165: bf16):
      "linalg.yield"(%164) {prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_2", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n41"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n43"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_2"} : (tensor<512x128xbf16>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %166 = "tensor.empty"() {prov.region_id = "dtype_cast_5", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<128x512xf32>
    %167 = "linalg.generic"(%163, %166) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb25(%168: bf16, %169: f32):
      %170 = "arith.extf"(%168) {prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%170) {prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_5", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n43"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n45"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<128x512xbf16>, tensor<128x512xf32>) -> tensor<128x512xf32>
    %171 = "tensor.collapse_shape"(%167) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "view_2", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n44"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n46"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x512xf32>) -> tensor<65536xf32>
    %172 = "tensor.expand_shape"(%171) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 16, 32>}> {prov.region_id = "view_2", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n44"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n46"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32xf32>
    %173 = "tensor.empty"() {prov.region_id = "abs_2", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %174 = "linalg.generic"(%172, %173) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb26(%175: f32, %176: f32):
      %177 = "math.absf"(%175) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%177) {prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_2", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n45"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n47"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %178 = "arith.constant"() <{value = 0xff800000 : f32}> {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : () -> f32
    %179 = "tensor.splat"(%178) {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x16xf32>
    %180 = "linalg.reduce"(%174, %179) <{dimensions = array<i64: 2>}> ({
    ^bb27(%181: f32, %182: f32):
      %183 = "arith.maximumf"(%181, %182) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%183) {prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_2", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n46"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n48"], prov.trace_role = "lowering", prov.aten = "aten.amax.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %184 = "tensor.empty"() {prov.region_id = "minmax_2", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %185 = "linalg.generic"(%180, %184) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb28(%186: f32, %187: f32):
      %188 = "arith.constant"() <{value = 1.1920929e-07 : f32}> {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : () -> f32
      %189 = "arith.cmpf"(%186, %188) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %190 = "arith.select"(%189, %188, %186) {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%190) {prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_2", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n47"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n49"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %191 = "tensor.empty"() {prov.region_id = "log2_1", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %192 = "linalg.generic"(%185, %191) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb29(%193: f32, %194: f32):
      %195 = "math.log2"(%193) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%195) {prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "log2_1", prov._pattern_hint = "log2", prov.op = "log2", prov.source_node_ids = ["g:prepared:root:n48"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n50"], prov.trace_role = "lowering", prov.aten = "aten.log2.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %196 = "tensor.empty"() {prov.region_id = "floor_1", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %197 = "linalg.generic"(%192, %196) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb30(%198: f32, %199: f32):
      %200 = "math.floor"(%198) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%200) {prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "floor_1", prov._pattern_hint = "floor", prov.op = "floor", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n49"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n51"], prov.trace_role = "lowering", prov.aten = "aten.floor.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %201 = "tensor.empty"() {prov.region_id = "minmax_3", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %202 = "linalg.generic"(%197, %201) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb31(%203: f32, %204: f32):
      %205 = "arith.constant"() <{value = -23 : i64}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : () -> i64
      %206 = "arith.sitofp"(%205) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i64) -> f32
      %207 = "arith.cmpf"(%203, %206) <{predicate = 4 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %208 = "arith.select"(%207, %206, %203) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      %209 = "arith.constant"() <{value = 127 : i64}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : () -> i64
      %210 = "arith.sitofp"(%209) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i64) -> f32
      %211 = "arith.cmpf"(%208, %210) <{predicate = 2 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      %212 = "arith.select"(%211, %210, %208) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (i1, f32, f32) -> f32
      "linalg.yield"(%212) {prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "minmax_3", prov.family = "minmax", prov._pattern_hint = "minmax", prov.op = "minmax", prov.source_node_ids = ["g:prepared:root:n50"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n52"], prov.trace_role = "lowering", prov.aten = "aten.clamp.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %213 = "tensor.empty"() {prov.region_id = "exp2_1", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : () -> tensor<128x16xf32>
    %214 = "linalg.generic"(%202, %213) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb32(%215: f32, %216: f32):
      %217 = "math.exp2"(%215) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%217) {prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "exp2_1", prov._pattern_hint = "exp2", prov.op = "exp2", prov.source_node_ids = ["g:prepared:root:n51"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n53"], prov.trace_role = "lowering", prov.aten = "aten.exp2.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>, tensor<128x16xf32>) -> tensor<128x16xf32>
    %218 = "tensor.collapse_shape"(%214) <{reassociation = [[0 : i64, 1 : i64]]}> {prov.region_id = "unsqueeze_2", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n52"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n54"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x16xf32>) -> tensor<2048xf32>
    %219 = "tensor.expand_shape"(%218) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]], static_output_shape = array<i64: 128, 16, 1>}> {prov.region_id = "unsqueeze_2", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n52"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n54"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<2048xf32>) -> tensor<128x16x1xf32>
    %220 = "tensor.empty"() {prov.region_id = "div_1", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %221 = "linalg.generic"(%172, %219, %220) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb33(%222: f32, %223: f32, %224: f32):
      %225 = "arith.divf"(%222, %223) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%225) {prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "div_1", prov._pattern_hint = "div", prov.op = "div", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n53"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n55"], prov.trace_role = "lowering", prov.aten = "aten.div.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x1xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %226 = "tensor.collapse_shape"(%221) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "unsqueeze_3", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n56"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n60"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %227 = "tensor.expand_shape"(%226) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 16, 32, 1>}> {prov.region_id = "unsqueeze_3", prov._pattern_hint = "unsqueeze", prov.op = "unsqueeze", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n56"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n60"], prov.trace_role = "lowering", prov.aten = "aten.unsqueeze.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32x1xf32>
    %228 = "tensor.empty"() {prov.region_id = "sub_1", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32x16xf32>
    %229 = "linalg.generic"(%227, %2, %228) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb34(%230: f32, %231: f32, %232: f32):
      %233 = "arith.subf"(%230, %231) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%233) {prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "sub_1", prov._pattern_hint = "sub", prov.op = "sub", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n57"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n61"], prov.trace_role = "lowering", prov.aten = "aten.sub.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32x1xf32>, tensor<16xf32>, tensor<128x16x32x16xf32>) -> tensor<128x16x32x16xf32>
    %234 = "tensor.empty"() {prov.region_id = "abs_3", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : () -> tensor<128x16x32x16xf32>
    %235 = "linalg.generic"(%229, %234) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb35(%236: f32, %237: f32):
      %238 = "math.absf"(%236) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering"} : (f32) -> f32
      "linalg.yield"(%238) {prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "abs_3", prov._pattern_hint = "abs", prov.op = "abs", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n58"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n62"], prov.trace_role = "lowering", prov.aten = "aten.abs.default", prov.orig_dtype = "float32"} : (tensor<128x16x32x16xf32>, tensor<128x16x32x16xf32>) -> tensor<128x16x32x16xf32>
    %239 = "arith.constant"() <{value = 0x7f800000 : f32}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : () -> f32
    %240 = "tensor.splat"(%239) {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x16x32xf32>
    %241 = "linalg.reduce"(%235, %240) <{dimensions = array<i64: 3>}> ({
    ^bb36(%242: f32, %243: f32):
      %244 = "arith.minimumf"(%242, %243) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%244) {prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x16x32x16xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %245 = "tensor.collapse_shape"(%241) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %246 = "tensor.expand_shape"(%245) <{reassociation = [[0 : i64, 1 : i64, 2 : i64, 3 : i64]], static_output_shape = array<i64: 128, 16, 32, 1>}> {prov.region_id = "reduce_3", prov.family = "reduce", prov._pattern_hint = "reduce", prov.op = "reduce", prov.source_node_ids = ["g:prepared:root:n59"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n63"], prov.trace_role = "lowering", prov.aten = "aten.amin.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x16x32x1xf32>
    %247 = "tensor.empty"() {prov.region_id = "compare_1", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : () -> tensor<128x16x32x16xi1>
    %248 = "linalg.generic"(%235, %246, %247) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb37(%249: f32, %250: f32, %251: i1):
      %252 = "arith.cmpf"(%249, %250) <{predicate = 1 : i64, fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering"} : (f32, f32) -> i1
      "linalg.yield"(%252) {prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering"} : (i1) -> ()
    }) {prov.region_id = "compare_1", prov.family = "compare", prov._pattern_hint = "compare", prov.op = "compare", prov.source_node_ids = ["g:prepared:root:n60"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n64"], prov.trace_role = "lowering", prov.aten = "aten.eq.Tensor", prov.orig_dtype = "bool"} : (tensor<128x16x32x16xf32>, tensor<128x16x32x1xf32>, tensor<128x16x32x16xi1>) -> tensor<128x16x32x16xi1>
    %253 = "arith.constant"() <{value = 1024 : i32}> {prov.region_id = "fill_1", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n61"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n65"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : () -> i32
    %254 = "tensor.splat"(%253) {prov.region_id = "fill_1", prov.family = "fill", prov._pattern_hint = "fill", prov.op = "fill", prov.source_node_ids = ["g:prepared:root:n61"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n65"], prov.trace_role = "lowering", prov.aten = "aten.full_like.default", prov.orig_dtype = "int32"} : (i32) -> tensor<16xi32>
    %255 = "tensor.empty"() {prov.region_id = "select_1", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : () -> tensor<128x16x32x16xi32>
    %256 = "linalg.generic"(%248, %3, %254, %255) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 3, 1>}> ({
    ^bb38(%257: i1, %258: i32, %259: i32, %260: i32):
      %261 = "arith.select"(%257, %258, %259) {prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      "linalg.yield"(%261) {prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering"} : (i32) -> ()
    }) {prov.region_id = "select_1", prov.family = "layout", prov._pattern_hint = "select", prov.op = "select", prov.source_node_ids = ["g:prepared:root:n62"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n66"], prov.trace_role = "lowering", prov.aten = "aten.where.self", prov.orig_dtype = "int32"} : (tensor<128x16x32x16xi1>, tensor<16xi32>, tensor<16xi32>, tensor<128x16x32x16xi32>) -> tensor<128x16x32x16xi32>
    %262 = "arith.constant"() <{value = 2147483647 : i32}> {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i32
    %263 = "arith.constant"() <{value = 9223372036854775807 : i64}> {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : () -> i64
    %264 = "tensor.splat"(%262) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i32) -> tensor<128x16x32xi32>
    %265 = "tensor.splat"(%263) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (i64) -> tensor<128x16x32xi64>
    %266, %267 = "linalg.generic"(%256, %264, %265) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<reduction>], operandSegmentSizes = array<i32: 1, 2>}> ({
    ^bb39(%268: i32, %269: i32, %270: i64):
      %271 = "linalg.index"() <{dim = 3 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : () -> index
      %272 = "arith.index_cast"(%271) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (index) -> i64
      %273 = "arith.cmpi"(%268, %269) <{predicate = 2 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %274 = "arith.cmpi"(%268, %269) <{predicate = 0 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i32) -> i1
      %275 = "arith.cmpi"(%272, %270) <{predicate = 6 : i64}> {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i64, i64) -> i1
      %276 = "arith.andi"(%274, %275) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %277 = "arith.ori"(%273, %276) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i1) -> i1
      %278 = "arith.select"(%277, %268, %269) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i32, i32) -> i32
      %279 = "arith.select"(%277, %272, %270) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i1, i64, i64) -> i64
      "linalg.yield"(%278, %279) {prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering"} : (i32, i64) -> ()
    }) {prov.region_id = "arg_reduce_1", prov.family = "arg_reduce", prov._pattern_hint = "aten_argmin", prov.op = "aten_argmin", prov.source_node_ids = ["g:prepared:root:n63"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n67"], prov.trace_role = "lowering", prov.aten = "aten.argmin.default", prov.orig_dtype = "int64"} : (tensor<128x16x32x16xi32>, tensor<128x16x32xi32>, tensor<128x16x32xi64>) -> (tensor<128x16x32xi32>, tensor<128x16x32xi64>)
    %280 = "tensor.empty"() {prov.region_id = "gather_1", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %281 = "linalg.generic"(%267, %280) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb40(%282: i64, %283: f32):
      %284 = "arith.index_cast"(%282) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (i64) -> index
      %285 = "tensor.extract"(%2, %284) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (tensor<16xf32>, index) -> f32
      "linalg.yield"(%285) {prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "gather_1", prov.family = "gather_scatter", prov._pattern_hint = "index_gather", prov.op = "index_gather", prov.source_node_ids = ["g:prepared:root:n64"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n68"], prov.trace_role = "lowering", prov.aten = "aten.index.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xi64>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %286 = "tensor.empty"() {prov.region_id = "mul_1", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : () -> tensor<128x16x32xf32>
    %287 = "linalg.generic"(%281, %219, %286) <{indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 2, 1>}> ({
    ^bb41(%288: f32, %289: f32, %290: f32):
      %291 = "arith.mulf"(%288, %289) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%291) {prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "mul_1", prov._pattern_hint = "mul", prov.op = "mul", prov.family = "elementwise", prov.source_node_ids = ["g:prepared:root:n65"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n69"], prov.trace_role = "lowering", prov.aten = "aten.mul.Tensor", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>, tensor<128x16x1xf32>, tensor<128x16x32xf32>) -> tensor<128x16x32xf32>
    %292 = "tensor.collapse_shape"(%287) <{reassociation = [[0 : i64, 1 : i64, 2 : i64]]}> {prov.region_id = "view_3", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n66"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n70"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<128x16x32xf32>) -> tensor<65536xf32>
    %293 = "tensor.expand_shape"(%292) <{reassociation = [[0 : i64, 1 : i64]], static_output_shape = array<i64: 128, 512>}> {prov.region_id = "view_3", prov._pattern_hint = "view", prov.op = "view", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n66"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n70"], prov.trace_role = "lowering", prov.aten = "aten.view.default", prov.orig_dtype = "float32"} : (tensor<65536xf32>) -> tensor<128x512xf32>
    %294 = "tensor.empty"() {prov.region_id = "dtype_cast_6", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : () -> tensor<128x512xbf16>
    %295 = "linalg.generic"(%293, %294) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb42(%296: f32, %297: bf16):
      %298 = "arith.truncf"(%296) {prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering"} : (f32) -> bf16
      "linalg.yield"(%298) {prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "dtype_cast_6", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n68"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n72"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "bfloat16"} : (tensor<128x512xf32>, tensor<128x512xbf16>) -> tensor<128x512xbf16>
    %299 = "tensor.empty"() {prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16"} : () -> tensor<512x128xbf16>
    %300 = "linalg.transpose"(%295, %299) <{permutation = array<i64: 1, 0>}> ({
    ^bb43(%301: bf16, %302: bf16):
      "linalg.yield"(%301) {prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering"} : (bf16) -> ()
    }) {prov.region_id = "permute_3", prov._pattern_hint = "permute", prov.op = "permute", prov.family = "layout", prov.source_node_ids = ["g:prepared:root:n69"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n73"], prov.trace_role = "lowering", prov.aten = "aten.permute.default", prov.orig_dtype = "bfloat16", prov.dispatch_id = "permute_3"} : (tensor<128x512xbf16>, tensor<512x128xbf16>) -> tensor<512x128xbf16>
    %303 = "tensor.empty"() {prov.region_id = "dtype_cast_7", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : () -> tensor<512x128xf32>
    %304 = "linalg.generic"(%300, %303) <{indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = [#linalg.iterator_type<parallel>, #linalg.iterator_type<parallel>], operandSegmentSizes = array<i32: 1, 1>}> ({
    ^bb44(%305: bf16, %306: f32):
      %307 = "arith.extf"(%305) {prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering"} : (bf16) -> f32
      "linalg.yield"(%307) {prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "dtype_cast_7", prov._pattern_hint = "dtype_cast", prov.op = "dtype_cast", prov.family = "cast", prov.source_node_ids = ["g:prepared:root:n71"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n75"], prov.trace_role = "lowering", prov.aten = "aten._to_copy.default", prov.orig_dtype = "float32"} : (tensor<512x128xbf16>, tensor<512x128xf32>) -> tensor<512x128xf32>
    %308 = "arith.constant"() <{value = 0.000000e+00 : f32}> {prov.region_id = "matmul_0", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : () -> f32
    %309 = "tensor.splat"(%308) {prov.region_id = "matmul_0", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : (f32) -> tensor<128x128xf32>
    %310 = "linalg.matmul"(%153, %304, %309) <{operandSegmentSizes = array<i32: 2, 1>, indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>, affine_map<(d0, d1, d2) -> (d2, d1)>, affine_map<(d0, d1, d2) -> (d0, d1)>]}> ({
    ^bb45(%311: f32, %312: f32, %313: f32):
      %314 = "arith.mulf"(%311, %312) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      %315 = "arith.addf"(%314, %313) <{fastmath = #arith.fastmath<none>}> {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32, f32) -> f32
      "linalg.yield"(%315) {prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering"} : (f32) -> ()
    }) {prov.region_id = "matmul_0", prov.op = "matmul", prov.family = "contraction", prov.source_node_ids = ["g:prepared:root:n72"], prov.origin_node_ids = ["g:original:root:n2", "g:quantized:root:n76"], prov.trace_role = "lowering", prov.aten = "aten.mm.default", prov.orig_dtype = "float32"} : (tensor<128x512xf32>, tensor<512x128xf32>, tensor<128x128xf32>) -> tensor<128x128xf32>
    "func.return"(%310) : (tensor<128x128xf32>) -> ()
  }) : () -> ()
}) {prov.level = "linalg-on-tensors", prov.quantization = "external:mx_gemmini", prov.quantization_manifest_sha256 = "7ae1df4a61306db7a8aedb226d85f9408e1c3201a04c7844344631a2a00ad2bd"} : () -> ()
