"""Inventory Nicolas's MX Makefile programs and direct archived source references.

A source hash in an evidence receipt is only provenance. It is not proof that
the entire C program was regenerated by the compiler or numerically qualified.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FIELDS = ("source_driver_sha256", "source_sha256", "source_file_sha256")
EXPECTED_RTL = "266c593f2cb51d7e3fe83fc0317072b585ac3c52"


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _revision(path: Path) -> str:
    return subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True).strip()


def _family(name: str) -> str:
    if name.startswith("matmul_tiled_asym_"):
        return "asymmetric_matrix"
    if name.startswith("matmul_tiled_"):
        return "other_tiled_matrix"
    if name.startswith("chain_"):
        return "chain"
    if name.startswith("vpu_"):
        return "vpu"
    if name.startswith("spad_requant"):
        return "spad_requant"
    return "other_mx"


def build_inventory(rtl_root: Path) -> dict:
    rtl_root = rtl_root.resolve()
    if _revision(rtl_root) != EXPECTED_RTL:
        raise ValueError("Nicolas MX inventory needs the pinned RTL revision")
    software = rtl_root / "software/gemmini-rocc-tests"
    source_dir = software / "bareMetalC"
    makefile = source_dir / "Makefile"
    content = makefile.read_text()
    match = re.search(r"^mx_tests = \\\n(.*?)^# Pull the gate", content, re.M | re.S)
    if match is None:
        raise ValueError("Nicolas MX Makefile roster changed")
    lines = match.group(1).splitlines()
    names = []
    for line in lines:
        value = line.strip().removesuffix("\\").strip()
        if value:
            if re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", value) is None:
                raise ValueError(f"unknown Nicolas MX test entry: {value}")
            names.append(value)
    if len(names) != len(set(names)) or not names:
        raise ValueError("Nicolas MX Makefile has duplicate or absent test entries")
    entries = []
    by_sha = {}
    for name in names:
        path = source_dir / f"{name}.c"
        if not path.is_file():
            raise ValueError(f"Nicolas MX test has no C source: {name}")
        digest = _sha(path)
        if digest in by_sha:
            raise ValueError("Nicolas MX test C sources have duplicate bytes")
        entry = {"name": name, "source_sha256": digest,
                 "family": _family(name), "evidence_references": []}
        entries.append(entry)
        by_sha[digest] = entry
    for path in sorted((ROOT / "docs/evidence").rglob("*.json")):
        # Exclude this report itself so repeated generation is idempotent.
        if path.parts[-2:] == ("nicolas_mx_source_inventory_266c593", "index.json"):
            continue
        data = json.loads(path.read_text())
        if not isinstance(data, dict):
            continue
        for field in SOURCE_FIELDS:
            entry = by_sha.get(data.get(field))
            if entry is None:
                continue
            entry["evidence_references"].append({
                "path": str(path.relative_to(ROOT)), "field": field,
                "sha256": _sha(path), "schema": data.get("schema"),
                "status": data.get("status"),
            })
    family_counts = {family: sum(entry["family"] == family for entry in entries)
                     for family in sorted({_family(name) for name in names})}
    return {
        "schema": "mx_gemmini.nicolas_mx_source_inventory.v1",
        "scope": "direct C source-hash references only; neither source execution nor compiler parity is implied",
        "rtl_revision": EXPECTED_RTL,
        "software_revision": _revision(software),
        "makefile_sha256": _sha(makefile),
        "programs": len(entries),
        "with_direct_hash_reference": sum(bool(entry["evidence_references"])
                                          for entry in entries),
        "without_direct_hash_reference": sum(not entry["evidence_references"]
                                             for entry in entries),
        "family_counts": family_counts,
        "entries": entries,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rtl-root", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = json.dumps(build_inventory(args.rtl_root), indent=2,
                         sort_keys=True) + "\n"
    if args.check:
        if not args.out.is_file() or args.out.read_text() != content:
            raise SystemExit("Nicolas MX source inventory differs from pinned evidence")
    else:
        if args.out.exists():
            parser.error(f"refusing to overwrite {args.out}")
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content)
    print(args.out)


if __name__ == "__main__":
    main()
